#!/usr/bin/env node

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { basename, dirname, extname, join, relative, resolve } from "node:path";
import {
  createAssetBundle,
  createConsumerValidationReport,
  inspectAsset,
  inspectAssetForTarget,
  type AssetEvidence,
  type AssetKind,
  type AssetPolicy,
  type ConsumerAssetRecord,
  type ConsumerCheckStatus,
  type ConsumerClunkInspection,
  type ConsumerFileRef,
  type ConsumerLaneEvidence,
  type ConsumerLaneOutput,
  type ConsumerProjectRecord,
  type ConsumerProvenance,
  type ConsumerRuntimeAttachment,
  type ConsumerRuntimeEvidence,
} from "../packages/core/src/index";
import { inspectEnvelope } from "../packages/core/src/contract";

const CLUNK_ROOT = resolve(import.meta.dirname, "..");
const DEFAULT_HARVEST_ROOT = "C:\\Users\\50106\\Desktop\\Harvest Frontier";
const DEFAULT_FORGE_ROOT = "C:\\Users\\50106\\Desktop\\FORGE FRONT";
const ZERO_HASH = "0".repeat(64);

interface Options {
  harvestRoot: string;
  forgeRoot: string;
  runId: string;
  outputPath: string;
  strict: boolean;
  requirePipelineRun: string | null;
  failOnStale: boolean;
}

interface ForgeGuards {
  requirePipelineRun: string | null;
  failOnStale: boolean;
}

interface GitInfo {
  head: string | null;
  dirty: boolean;
  dirtyEntryCount: number;
}

interface RuntimeCandidate {
  path: string;
  value: Record<string, unknown>;
  modifiedAt: number;
}

interface InspectionResult {
  record: ConsumerClunkInspection;
  evidence: AssetEvidence | null;
}

interface ForgeManifestAsset {
  id: string;
  assetId?: string;
  source?: FileManifestRef;
  derived?: FileManifestRef;
  runtime?: FileManifestRef;
  sourcePath?: string;
  derivedPath?: string;
  clunk?: Record<string, unknown>;
  evidencePaths?: Record<string, unknown>;
}

interface FileManifestRef {
  path?: string;
  sha256?: string;
  bytes?: number;
}

interface ReleaseLedger {
  path: string;
  releaseRunId: string | null;
  assetRunId: string | null;
  gameReadyRunId: string | null;
}

interface ForgePipelineResolution {
  path: string | null;
  /** The resolved manifest's run id (from its content, else its filename). */
  runId: string | null;
  source: "release-ledger" | "game-ready-run-id" | "latest-pipeline-schema" | "none";
  /** The latest release ledger's declared assetRunId, for freshness comparison. */
  ledger: ReleaseLedger | null;
}

function main(): void {
  try {
    const parsed = parseArgs(process.argv.slice(2));
    if (parsed === null) return;
    const options = resolveOptions(parsed);
    const outputPath = resolve(options.outputPath);
    assertOutputIsClunkOwned(outputPath, options.harvestRoot, options.forgeRoot);
    if (existsSync(outputPath)) throw new Error(`Output already exists; use a new --run-id: ${outputPath}`);
    mkdirSync(dirname(outputPath), { recursive: true });

    const runRoot = dirname(outputPath);
    const clunkGit = gitInfo(CLUNK_ROOT);
    const harvest = collectHarvestFrontier(options.harvestRoot, runRoot, options.runId);
    const forge = collectForgeFront(options.forgeRoot, runRoot, options.runId, {
      requirePipelineRun: options.requirePipelineRun,
      failOnStale: options.failOnStale,
    });
    const report = createConsumerValidationReport({
      runId: options.runId,
      generatedAt: new Date().toISOString(),
      clunk: {
        root: CLUNK_ROOT,
        gitHead: clunkGit.head,
        coreBuildId: computeCoreBuildId(CLUNK_ROOT, clunkGit),
      },
      projects: [harvest.project, forge.project],
      readOnly: true,
      limitations: [
        "Consumer checkouts are read-only inputs; this run writes only below the Clunk evidence directory.",
        "Clunk structural inspection, consumer runtime evidence, and human player-facing review remain separate gates.",
        "A project-level runtime PASS does not prove that every individual asset was visually approved.",
        "coreBuildId is a content hash of the Clunk executing code tree (packages/core/src + scripts); a report generated by different bytes carries a different coreBuildId.",
      ],
    });
    writeJsonExclusive(outputPath, report);

    const result = {
      ok: report.summary.integrityFailureCount === 0,
      reportPath: outputPath,
      runId: report.runId,
      status: report.summary.readiness,
      coreBuildId: report.clunk.coreBuildId,
      forgePipeline: {
        manifestPath: forge.resolution.path,
        manifestRunId: forge.resolution.runId,
        source: forge.resolution.source,
        latestReleaseLedgerAssetRunId: forge.resolution.ledger?.assetRunId ?? null,
      },
      summary: report.summary,
      projects: report.projects.map((project) => ({
        id: project.id,
        status: project.status,
        gitHead: project.gitHead,
        assetCount: project.assets.length,
        pipelineAssetCount: project.pipelineAssetCount,
        laneAssetCount: project.laneAssetCount,
        runtime: project.runtime.status,
        humanReview: project.runtime.humanReview,
      })),
    };
    process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
    if (report.summary.integrityFailureCount > 0) process.exitCode = 1;
    else if (options.strict && report.summary.readiness !== "VALIDATED") process.exitCode = 2;
  } catch (error) {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
    process.exitCode = 2;
  }
}

function parseArgs(args: readonly string[]): Partial<Options> | null {
  const result: Partial<Options> = {};
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--help" || arg === "-h") {
      process.stdout.write([
        "Usage: npm run consumer:audit -- [options]",
        "",
        "  --run-id <id>                Immutable evidence run id",
        "  --harvest-root <path>        Harvest Frontier checkout",
        "  --forge-root <path>          FORGE FRONT checkout",
        "  --out <path>                 Clunk-side report path",
        "  --strict                     Return exit 2 while any non-blocking gate remains",
        "  --require-pipeline-run <id>  Fail unless the resolved FF pipeline manifest is this run id",
        "  --fail-on-stale              Fail if the resolved manifest is not the latest release ledger's assetRunId",
      ].join("\n") + "\n");
      return null;
    }
    if (arg === "--strict") {
      result.strict = true;
      continue;
    }
    if (arg === "--fail-on-stale") {
      result.failOnStale = true;
      continue;
    }
    if (arg === "--run-id" || arg === "--harvest-root" || arg === "--forge-root" || arg === "--out" || arg === "--require-pipeline-run") {
      const value = args[index + 1];
      if (!value || value.startsWith("--")) throw new Error(`${arg} requires a value.`);
      index += 1;
      if (arg === "--run-id") result.runId = value;
      if (arg === "--harvest-root") result.harvestRoot = value;
      if (arg === "--forge-root") result.forgeRoot = value;
      if (arg === "--out") result.outputPath = value;
      if (arg === "--require-pipeline-run") result.requirePipelineRun = value;
      continue;
    }
    throw new Error(`Unknown option: ${arg}`);
  }
  return result;
}

function resolveOptions(input: Partial<Options>): Options {
  const runId = input.runId ?? makeRunId();
  if (!/^[A-Za-z0-9][A-Za-z0-9._-]{0,119}$/.test(runId)) {
    throw new Error("--run-id must contain only letters, numbers, dot, underscore, or hyphen.");
  }
  const harvestRoot = resolve(input.harvestRoot ?? DEFAULT_HARVEST_ROOT);
  const forgeRoot = resolve(input.forgeRoot ?? DEFAULT_FORGE_ROOT);
  const outputPath = input.outputPath
    ? resolve(input.outputPath)
    : join(CLUNK_ROOT, ".clunk-evidence", "consumer-validation", runId, "report.json");
  return {
    harvestRoot,
    forgeRoot,
    runId,
    outputPath,
    strict: input.strict === true,
    requirePipelineRun: input.requirePipelineRun ?? null,
    failOnStale: input.failOnStale === true,
  };
}

function makeRunId(): string {
  return `clunk-consumer-${new Date().toISOString().replace(/[-:.TZ]/g, "")}`;
}

function collectHarvestFrontier(root: string, runRoot: string, runId: string): { project: ConsumerProjectRecord; handoffPath: string } {
  const runtimeRoot = join(root, "public", "assets", "runtime");
  const git = gitInfo(root);
  const projectEvidenceRoot = join(runRoot, "harvest-frontier");
  mkdirSync(projectEvidenceRoot, { recursive: true });
  const provenance = harvestProvenance(root);
  const runtimeEvidence = latestHarvestRuntimeEvidence(root, git.head);
  const glbPaths = existsSync(runtimeRoot)
    ? readdirSync(runtimeRoot, { withFileTypes: true })
      .filter((entry) => entry.isFile() && extname(entry.name).toLowerCase() === ".glb")
      .map((entry) => join(runtimeRoot, entry.name))
      .sort((left, right) => basename(left).localeCompare(basename(right)))
    : [];

  const assets: ConsumerAssetRecord[] = [];
  const handoffAssets: Record<string, unknown>[] = [];
  for (const filePath of glbPaths) {
    const id = basename(filePath, ".glb");
    const source = fileRef(filePath);
    const targetInspection = inspectForConsumer(
      source,
      "harvest-frontier-web-three",
      "3d-model",
      `${runId}-hf-${id}`,
      join(projectEvidenceRoot, `${safeFileName(id)}-clunk-inspection.json`),
      "source",
    );
    const compatibility = compatibilityInspection(filePath, source, join(projectEvidenceRoot, `${safeFileName(id)}-pc-inspection.json`));
    const runtimeInspection = source.hashVerified
      ? { ...targetInspection.record, input: "runtime" as const }
      : undefined;
    const integrity = checksToIntegrity({
      sourceHash: source.hashVerified ? "PASS" : "FAIL",
      runtimeHash: source.hashVerified ? "PASS" : "FAIL",
      clunkInputHash: targetInspection.record.inputHash === source.sha256 ? "PASS" : "FAIL",
      compatibilityInspection: compatibility.report.inputHash === source.sha256 ? "PASS" : "FAIL",
    });
    const runtimeAttachment = {
      status: !source.hashVerified ? "FAIL" as const : runtimeEvidence.status === "PASS" ? "PASS" as const : "GAP" as const,
      pathPresent: source.hashVerified,
      observation: source.hashVerified && runtimeEvidence.status === "PASS" ? "PATH_ONLY" as const : "NOT_OBSERVED" as const,
      note: "현재 HF 런타임 증거는 프로젝트·화면 범위이며, GLB별 loader 사용은 별도 계측되지 않았습니다.",
      ...(runtimeEvidence.evidencePath ? { evidencePath: runtimeEvidence.evidencePath } : {}),
    };
    assets.push({
      id,
      projectId: "harvest-frontier",
      kind: "3d-model",
      role: id.includes("lod1") ? "near/far LOD runtime model" : "runtime model",
      source,
      runtime: source,
      clunk: targetInspection.record,
      ...(runtimeInspection ? { runtimeInspection } : {}),
      runtimeAttachment,
      provenance,
      integrity,
    });
    handoffAssets.push({
      fileName: basename(filePath),
      sourcePath: filePath,
      bytes: source.bytes,
      sha256: source.sha256,
      clunkInspection: compatibility.envelope,
    });
  }

  const handoffPath = join(projectEvidenceRoot, "harvest-frontier-handoff.json");
  writeJsonExclusive(handoffPath, {
    schemaVersion: 1,
    generatedAt: new Date().toISOString(),
    sourceProject: root,
    runtimeRoot,
    readOnly: true,
    optimizerAllowed: false,
    clunkProfile: "pc",
    ruleSetId: "clunk-game-ready-v1",
    assets: handoffAssets,
    collaborationBoundary: [
      "This compatibility manifest reads current Harvest Frontier GLB bytes and never writes to the Harvest Frontier checkout.",
      "Clunk target inspection and Harvest semantic/runtime validation remain separate gates.",
      "A changed SHA-256 requires a new run and invalidates earlier evidence for that asset.",
    ],
  });
  const handoffCheck = runHarvestVerifier(root, handoffPath);
  const checks: Record<string, ConsumerCheckStatus> = {
    sourceCheckout: git.head ? "PASS" : "NOT_CHECKED",
    provenanceManifest: provenance.status === "PASS" ? "PASS" : provenance.status === "FAIL" ? "FAIL" : "NOT_CHECKED",
    currentClunkHandoff: handoffCheck.status,
    currentRuntimeEvidence: runtimeEvidence.status === "PASS" ? "PASS" : runtimeEvidence.status === "FAIL" ? "FAIL" : "NOT_CHECKED",
  };
  const project: ConsumerProjectRecord = {
    id: "harvest-frontier",
    name: "Harvest Frontier",
    root,
    gitHead: git.head,
    dirty: git.dirty,
    readOnly: true,
    runtime: runtimeEvidence,
    checks,
    assets,
    pipelineAssetCount: assets.length,
    laneAssetCount: 0,
    status: "PASS_WITH_GAPS",
    limitations: [
      "Clunk inspection is fresh for the current GLB bytes, but the target import/runtime stages are not executed by Clunk itself.",
      "The current game evidence proves a shipped-path game session, not a per-GLB loader telemetry map.",
      "Human player-facing visual review remains NOT_EVALUATED in the imported evidence.",
    ],
  };
  return { project, handoffPath };
}

function collectForgeFront(
  root: string,
  runRoot: string,
  runId: string,
  guards: ForgeGuards,
): { project: ConsumerProjectRecord; resolution: ForgePipelineResolution } {
  const projectEvidenceRoot = join(runRoot, "forge-front");
  mkdirSync(projectEvidenceRoot, { recursive: true });
  const git = gitInfo(root);
  // The release ledger is the shipping authority for BOTH pointers: which
  // pipeline manifest is live and which game-ready run proved it loaded. The
  // old newest-v8 pick silently pinned an ancient run once FF's harness moved
  // to v12/v13 schemas.
  const ledger = latestReleaseLedger(root);
  const gameReady = latestForgeGameReadyEvidence(root, ledger?.gameReadyRunId ?? undefined);
  const resolution = resolveForgePipeline(root, gameReady.value);
  applyForgeFreshnessGuards(resolution, guards);
  const pipelinePath = resolution.path;
  const pipeline = pipelinePath ? readRecord(pipelinePath) : null;
  const pipelineHash = pipelinePath ? fileRef(pipelinePath) : missingFileRef(join(root, "artifacts", "clunk", "evidence", "pipeline-manifest.json"));
  const runtimeAssets = forgeRuntimeAssets(gameReady.value);
  const pipelineAssets: ConsumerAssetRecord[] = [];
  const pipelineIds = new Set<string>();

  for (const raw of arrayRecords(pipeline?.assets)) {
    const record = {
      ...raw,
      id: stringValue(raw.id) ?? stringValue(raw.assetId) ?? "",
    } as unknown as ForgeManifestAsset;
    if (!record.id) continue;
    pipelineIds.add(record.id);
    const sourcePath = record.source?.path ?? record.sourcePath;
    const derivedPath = record.derived?.path ?? record.derivedPath;
    const runtimePath = record.runtime?.path ?? runtimePathFromEvidence(root, runtimeAssets, record);
    const source = sourcePath ? fileRef(sourcePath) : missingFileRef(join(root, "artifacts", "clunk", "source", `${record.id}-source.png`));
    const derived = derivedPath ? fileRef(derivedPath) : missingFileRef(join(root, "artifacts", "clunk", "derived", `${record.id}.png`));
    const runtime = runtimePath ? fileRef(runtimePath) : missingFileRef(join(root, "public", "assets", "clunk", record.id));
    const sourceInspection = inspectForConsumer(
      source,
      "yeongheo-pixi-2d",
      "2d-image",
      `${runId}-ff-${record.id}-source`,
      join(projectEvidenceRoot, `${safeFileName(record.id)}-source-clunk-inspection.json`),
      "source",
    );
    const runtimeInspection = inspectForConsumer(
      runtime,
      "yeongheo-pixi-2d",
      "2d-image",
      `${runId}-ff-${record.id}-runtime`,
      join(projectEvidenceRoot, `${safeFileName(record.id)}-runtime-clunk-inspection.json`),
      "runtime",
    );
    const runtimeEntry = runtimeAssets.find((candidate) => pathMatchesRuntime(candidate.url, runtime.path, root));
    const runtimeLoaded = runtimeEntry?.loaded === true;
    const runtimeExternal = runtimeEntry?.externalRequests === true;
    const runtimeLoadedValue = runtimeEntry?.loaded;
    const runtimeExternalValue = runtimeEntry?.externalRequests;
    const pipelineClunk = record.clunk ?? {};
    const checks = checksToIntegrity({
      sourceHash: matchesManifest(source, record.source) ? "PASS" : "FAIL",
      derivedHash: matchesManifest(derived, record.derived) ? "PASS" : "FAIL",
      runtimeHash: matchesManifest(runtime, record.runtime) ? "PASS" : "FAIL",
      sourceClunk: sourceInspection.record.inputHash === source.sha256 ? "PASS" : "FAIL",
      runtimeClunk: runtimeInspection.record.inputHash === runtime.sha256 ? "PASS" : "FAIL",
      spriteAudit: pipelineClunk.spriteAuditStatus === "PASS" ? "PASS" : "FAIL",
      runtimeLoad: runtimeLoaded && !runtimeExternal ? "PASS" : "FAIL",
      pipelineManifest: pipelineHash.hashVerified ? "PASS" : "FAIL",
    });
    const provenance = forgeProvenance(record, pipelinePath, pipelineHash);
    pipelineAssets.push({
      id: record.id,
      projectId: "forge-front",
      kind: "2d-image",
      role: "Clunk-promoted PixiJS runtime asset",
      source,
      derived,
      runtime,
      clunk: sourceInspection.record,
      runtimeInspection: runtimeInspection.record,
      runtimeAttachment: {
        status: runtimeLoaded && !runtimeExternal && runtime.hashVerified ? "PASS" : runtime.hashVerified ? "GAP" : "FAIL",
        pathPresent: runtime.hashVerified,
        observation: runtimeLoaded && !runtimeExternal ? "LOADED" : runtime.hashVerified ? "PATH_ONLY" : "NOT_OBSERVED",
        ...(typeof runtimeLoadedValue === "boolean" ? { loaded: runtimeLoadedValue } : {}),
        ...(typeof runtimeExternalValue === "boolean" ? { externalRequests: runtimeExternalValue } : {}),
        ...(gameReady.path ? { evidencePath: gameReady.path } : {}),
        note: runtimeEntry ? "FORGE FRONT game-ready evidence의 runtime asset URL·loaded 값을 해시 경로와 대조했습니다." : "게임 런타임 evidence에서 대응 URL을 찾지 못했습니다.",
      },
      provenance,
      integrity: checks,
    });
  }

  const laneAssets = collectForgeLaneAssets(root, projectEvidenceRoot, runId, pipelineIds, runtimeAssets, gameReady.path);
  const assets = [...pipelineAssets, ...laneAssets];

  const runtime = forgeRuntimeEvidence(root, gameReady, runtimeAssets);
  const checks: Record<string, ConsumerCheckStatus> = {
    sourceCheckout: git.head ? "PASS" : "NOT_CHECKED",
    pipelineManifest: pipeline && pipelineHash.hashVerified ? "PASS" : "FAIL",
    runtimeEvidence: runtime.status === "PASS" ? "PASS" : runtime.status === "FAIL" ? "FAIL" : "NOT_CHECKED",
    // The runtime asset-count gate is a pipeline-lane signal only; lane deliveries
    // are presentation/support assets and are not part of the Pixi runtime evidence.
    runtimeAssetCount: runtime.expectedAssetCount === pipelineAssets.length && runtime.loadedAssetCount === pipelineAssets.length ? "PASS" : "FAIL",
  };
  const project: ConsumerProjectRecord = {
    id: "forge-front",
    name: "FORGE FRONT",
    root,
    gitHead: git.head,
    dirty: git.dirty,
    readOnly: true,
    runtime,
    checks,
    assets,
    pipelineAssetCount: pipelineAssets.length,
    laneAssetCount: laneAssets.length,
    status: "PASS_WITH_GAPS",
    limitations: [
      "현재 게임-ready evidence는 자동 브라우저·런타임 로드를 증명하지만 human visual review는 NOT_EVALUATED입니다.",
      "Clunk Core import stage는 기존 consumer pipeline에서 ENVIRONMENT_UNAVAILABLE로 보존되어 있습니다.",
      "이 실행은 FORGE FRONT 게임 로직이나 파일을 수정하지 않았습니다.",
      "Lane 자산(presentation/support delivery)은 DOM/CSS 소비 경로이며 Pixi runtime asset evidence와 별개 게이트로 계측됩니다.",
    ],
  };
  return { project, resolution };
}

function inspectForConsumer(
  ref: ConsumerFileRef,
  targetProfileId: string,
  assetKind: AssetKind,
  runId: string,
  evidencePath: string,
  input: "source" | "derived" | "runtime",
): InspectionResult {
  if (!ref.hashVerified) {
    return {
      record: {
        input,
        targetProfileId,
        ruleSetId: assetKind === "3d-model" ? "harvest-frontier-runtime-v1" : "pixi-sprite-atlas-v1",
        status: "BLOCKED",
        productionReady: false,
        inputHash: ref.sha256,
        evidencePath,
      },
      evidence: null,
    };
  }
  const bytes = new Uint8Array(readFileSync(ref.path));
  const evidence = inspectAssetForTarget({
    runId,
    sourcePath: ref.path,
    fileName: basename(ref.path),
    bytes,
    targetProfileId,
    assetKind,
  });
  writeJsonExclusive(evidencePath, evidence);
  return {
    record: {
      input,
      targetProfileId,
      ruleSetId: evidence.ruleSetId ?? evidence.target.semanticRules?.[0] ?? "unknown",
      status: evidence.status,
      productionReady: evidence.productionReady,
      inputHash: evidence.source.sha256,
      evidencePath,
      warningCount: evidence.qualityWarnings.length,
      hardBlockerCount: evidence.findings.filter((finding) => finding.severity === "ERROR" || finding.severity === "CRITICAL").length,
    },
    evidence,
  };
}

function compatibilityInspection(
  filePath: string,
  ref: ConsumerFileRef,
  evidencePath: string,
): { report: ReturnType<typeof inspectAsset>; envelope: ReturnType<typeof inspectEnvelope> } {
  const policy: AssetPolicy = { profileId: "pc" };
  const report = inspectAsset(createAssetBundle(basename(filePath), new Uint8Array(readFileSync(filePath))), policy);
  const envelope = inspectEnvelope(report);
  writeJsonExclusive(evidencePath, envelope);
  if (report.inputHash !== ref.sha256) throw new Error(`Compatibility inspection hash mismatch: ${filePath}`);
  return { report, envelope };
}

function harvestProvenance(root: string): ConsumerProvenance {
  const paths = [join(root, "assets", "provenance.json"), join(root, "public", "assets", "provenance.json")];
  const refs = paths.map((path) => resolve(path));
  const files = refs.map(fileRef);
  const same = files.every((file) => file.hashVerified) && new Set(files.map((file) => file.sha256)).size === 1;
  return {
    status: same ? "PASS" : files.some((file) => file.hashVerified) ? "FAIL" : "GAP",
    refs,
    ...(files[0]?.hashVerified ? { manifestHash: files[0].sha256 } : {}),
    note: same ? "Harvest Frontier provenance manifests are byte-identical for this run." : "Both provenance manifests could not be proven byte-identical.",
  };
}

function forgeProvenance(record: ForgeManifestAsset, pipelinePath: string | null, pipelineHash: ConsumerFileRef): ConsumerProvenance {
  const refs = [
    pipelinePath,
    stringPath(record.source?.path ?? record.sourcePath),
    stringPath(record.derived?.path ?? record.derivedPath),
    stringPath(record.runtime?.path),
    stringPath(record.evidencePaths?.inspect),
    stringPath(record.evidencePaths?.spriteAudit),
  ].filter((value): value is string => value !== null).map((path) => resolve(path));
  const licenseStatus = stringValue((record.source as Record<string, unknown> | undefined)?.licenseStatus);
  const status = pipelineHash.hashVerified && refs.length >= 3 && Boolean(licenseStatus) ? "PASS" : refs.length > 0 ? "GAP" : "FAIL";
  return {
    status,
    refs,
    ...(pipelineHash.hashVerified ? { manifestHash: pipelineHash.sha256 } : {}),
    note: licenseStatus ? `licenseStatus=${licenseStatus}` : "원본 라이선스 상태가 pipeline manifest에 없습니다.",
  };
}

function latestHarvestRuntimeEvidence(root: string, sourceHead: string | null): ConsumerRuntimeEvidence {
  const verificationRoot = join(root, ".logs", "verification");
  const candidate = latestJson(verificationRoot, (value) => {
    const shippedPath = value.shippedPath === true;
    const status = passValue(value.status);
    const current = sourceHead === null || value.sourceHead === undefined || value.sourceHead === sourceHead;
    return shippedPath && status && current && harvestScreenshotPaths(value).length > 0;
  });
  if (!candidate) {
    return {
      status: "UNAVAILABLE",
      scope: "project",
      humanReview: "NOT_EVALUATED",
      productionReady: false,
      note: "현재 체크아웃과 연결되는 shipped-path Harvest Frontier runtime evidence를 찾지 못했습니다.",
    };
  }
  const value = candidate.value;
  const screenshots = harvestScreenshotPaths(value).map((path) => fileRef(resolve(root, path)));
  const missingCapture = screenshots.some((file) => !file.hashVerified);
  const errors = numberValue(value.consoleErrorCount) ?? 0;
  const warnings = numberValue(value.consoleWarningCount) ?? 0;
  return {
    status: !missingCapture && errors === 0 && warnings === 0 ? "PASS" : "FAIL",
    scope: "project",
    ...(stringValue(value.runId) ? { runId: stringValue(value.runId)! } : {}),
    evidencePath: candidate.path,
    sourceCommit: stringValue(value.sourceHead),
    shippedPath: true,
    pageErrors: errors,
    pageWarnings: warnings,
    humanReview: "NOT_EVALUATED",
    productionReady: false,
    evidenceFiles: screenshots,
    note: "프로젝트·화면 범위의 shipped-path 자동 검증입니다. 개별 GLB loader 사용과 사람의 시각 승인은 별도입니다.",
  };
}

function harvestScreenshotPaths(value: Record<string, unknown>): string[] {
  const flow = asRecord(value.flow);
  const flowScreenshots = arrayStrings(flow?.screenshots);
  if (flowScreenshots.length > 0) return flowScreenshots;
  const screenshot = asRecord(value.screenshot);
  const screenshotPath = stringValue(screenshot?.path);
  return screenshotPath ? [screenshotPath] : [];
}

function latestForgeGameReadyEvidence(root: string, pinnedRunId?: string): RuntimeCandidate {
  const gameReadyRoot = join(root, "artifacts", "clunk", "evidence", "game-ready");
  // Version-agnostic: FF's harness bumps the schema suffix (v8 -> v12 -> v13)
  // while keeping the runtimeAssets contract; an exact-version pin silently
  // froze the audit on the last v8 run from 08-28.
  const isGameReadyEvidence = (value: Record<string, unknown>) =>
    String(value.schema ?? "").startsWith("forge-front.game-ready-evidence.v");
  if (pinnedRunId && /^[A-Za-z0-9._-]{1,120}$/.test(pinnedRunId)) {
    const pinnedDir = join(gameReadyRoot, pinnedRunId);
    if (existsSync(pinnedDir)) {
      const pinned = latestJson(pinnedDir, isGameReadyEvidence);
      if (pinned) return pinned;
    }
  }
  const candidate = latestJson(gameReadyRoot, isGameReadyEvidence);
  if (!candidate) throw new Error(`FORGE FRONT game-ready evidence not found below ${root}`);
  return candidate;
}

/**
 * Resolve which FF pipeline manifest to audit.
 *
 * Priority:
 *   1. The newest release-gate ledger's references.assetRunId -> clunk-manifest-<assetRunId>.json.
 *      This is what FF actually ships, so it is the authoritative pointer.
 *   2. The game-ready evidence's assetPipelineRunId (legacy behaviour).
 *   3. The newest clunk-pipeline.v1 manifest by mtime (last-resort fallback).
 */
function resolveForgePipeline(root: string, gameReady: Record<string, unknown>): ForgePipelineResolution {
  const evidenceRoot = join(root, "artifacts", "clunk", "evidence");
  const ledger = latestReleaseLedger(root);

  if (ledger?.assetRunId) {
    const fromLedger = join(evidenceRoot, `clunk-manifest-${ledger.assetRunId}.json`);
    if (existsSync(fromLedger)) {
      return { path: fromLedger, runId: manifestRunId(fromLedger), source: "release-ledger", ledger };
    }
  }

  const gameReadyRunId = stringValue(gameReady.assetPipelineRunId);
  if (gameReadyRunId) {
    const exact = join(evidenceRoot, `clunk-manifest-${gameReadyRunId}.json`);
    if (existsSync(exact)) {
      return { path: exact, runId: manifestRunId(exact), source: "game-ready-run-id", ledger };
    }
  }

  const candidate = latestJson(evidenceRoot, (value) => value.schema === "forge-front.clunk-pipeline.v1");
  if (candidate) {
    return { path: candidate.path, runId: manifestRunId(candidate.path), source: "latest-pipeline-schema", ledger };
  }
  return { path: null, runId: null, source: "none", ledger };
}

/**
 * Find the newest release-gate ledger under artifacts/clunk/evidence/release.
 *
 * "Newest" is ranked by the FF-<YYYYMMDDTHHMMSS>KST timestamp embedded in the
 * folder name, not mtime: git checkouts and fixture regeneration reset mtimes,
 * and some release folders are fixtures whose recent mtime would otherwise mask
 * the real newest ledger. mtime is only a tiebreaker for equal timestamps.
 */
function latestReleaseLedger(root: string): ReleaseLedger | null {
  const releaseRoot = join(root, "artifacts", "clunk", "evidence", "release");
  if (!existsSync(releaseRoot)) return null;
  const candidates: { path: string; ts: string; mtime: number; value: Record<string, unknown> }[] = [];
  for (const entry of readdirSync(releaseRoot, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const summaryPath = join(releaseRoot, entry.name, "release-gate-summary.json");
    if (!existsSync(summaryPath)) continue;
    const value = readRecord(summaryPath);
    if (!value || value.schema !== "forge-front.release-gate-evidence.v1") continue;
    const match = /FF-(\d{8}T\d{6})KST/.exec(entry.name);
    candidates.push({ path: summaryPath, ts: match ? match[1] : "", mtime: statSync(summaryPath).mtimeMs, value });
  }
  if (candidates.length === 0) return null;
  candidates.sort((left, right) => right.ts.localeCompare(left.ts) || right.mtime - left.mtime || right.path.localeCompare(left.path));
  const best = candidates[0];
  const references = asRecord(best.value.references);
  return {
    path: best.path,
    releaseRunId: stringValue(best.value.releaseRunId),
    assetRunId: stringValue(references?.assetRunId) ?? stringValue(best.value.assetRunId),
    gameReadyRunId: stringValue(references?.gameReadyRunId) ?? stringValue(best.value.gameReadyRunId),
  };
}

function applyForgeFreshnessGuards(resolution: ForgePipelineResolution, guards: ForgeGuards): void {
  if (guards.requirePipelineRun && resolution.runId !== guards.requirePipelineRun) {
    throw new Error(
      `--require-pipeline-run ${guards.requirePipelineRun}, but the resolver selected ${resolution.runId ?? "(no manifest)"} `
      + `(${resolution.path ?? "no pipeline manifest found"}).`,
    );
  }
  if (guards.failOnStale) {
    const ledgerAssetRunId = resolution.ledger?.assetRunId ?? null;
    if (!ledgerAssetRunId) {
      throw new Error("--fail-on-stale: no release-gate ledger assetRunId was found, so pipeline freshness cannot be proven.");
    }
    if (resolution.runId !== ledgerAssetRunId) {
      throw new Error(
        `--fail-on-stale: resolved pipeline manifest run ${resolution.runId ?? "(none)"} does not match the latest release `
        + `ledger assetRunId ${ledgerAssetRunId} (${resolution.ledger?.path ?? "unknown ledger"}).`,
      );
    }
  }
}

/** The manifest's declared runId, falling back to the clunk-manifest-<runId>.json filename. */
function manifestRunId(manifestPath: string): string | null {
  const record = readRecord(manifestPath);
  const declared = stringValue(record?.runId);
  if (declared) return declared;
  const match = /clunk-manifest-(.+)\.json$/.exec(basename(manifestPath));
  return match ? match[1] : null;
}

/**
 * Discover FF presentation/support lane deliveries under public/assets/clunk/*.
 *
 * A sidecar is a lane delivery when source.manifestPath exists AND outputs[] is
 * an array (verified against the real FF sidecars: pipeline sidecars carry
 * derived+runtime and no manifestPath/outputs). Pipeline assets already enter
 * through the manifest, so any sidecar whose assetId collides with a pipeline id
 * is skipped to avoid double counting. Every output's runtime bytes are
 * re-hashed and compared against the vendor-declared values.
 */
function collectForgeLaneAssets(
  root: string,
  projectEvidenceRoot: string,
  runId: string,
  pipelineIds: ReadonlySet<string>,
  runtimeAssets: readonly Record<string, unknown>[],
  gameReadyPath: string | null,
): ConsumerAssetRecord[] {
  const laneRoot = join(root, "public", "assets", "clunk");
  if (!existsSync(laneRoot)) return [];
  const assets: ConsumerAssetRecord[] = [];
  const dirs = readdirSync(laneRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort((left, right) => left.localeCompare(right));

  for (const dir of dirs) {
    const sidecarPath = join(laneRoot, dir, "clunk-evidence.json");
    if (!existsSync(sidecarPath)) continue;
    const value = readRecord(sidecarPath);
    if (!value) continue;
    const source = asRecord(value.source);
    const manifestPath = stringValue(source?.manifestPath);
    // Discriminator: lane = source.manifestPath present AND outputs[] is an array.
    if (!manifestPath || !Array.isArray(value.outputs)) continue;
    const outputs = arrayRecords(value.outputs);
    if (outputs.length === 0) continue;
    const deliveryAssetId = stringValue(value.assetId);
    if (!deliveryAssetId) continue;
    // Double-count guard: never re-count an asset the pipeline manifest already carries.
    if (pipelineIds.has(deliveryAssetId) || pipelineIds.has(dir)) continue;

    const integrityChecks: Record<string, ConsumerCheckStatus> = {};
    const laneOutputs: ConsumerLaneOutput[] = [];
    for (const raw of outputs) {
      const outputId = stringValue(raw.id) ?? `output-${laneOutputs.length}`;
      const runtimePath = stringValue(raw.runtimePath);
      const declaredSha = stringValue(raw.runtimeSha256);
      const declaredBytes = numberValue(raw.runtimeBytes) ?? 0;
      const runtime = runtimePath ? fileRef(runtimePath) : missingFileRef(join(laneRoot, dir, `${safeFileName(outputId)}.png`));
      const hashCheck: ConsumerCheckStatus = runtime.hashVerified && declaredSha !== null && runtime.sha256.toLowerCase() === declaredSha.toLowerCase() ? "PASS" : "FAIL";
      const bytesCheck: ConsumerCheckStatus = runtime.hashVerified && runtime.bytes === declaredBytes ? "PASS" : "FAIL";
      const dims = asRecord(raw.dimensions);
      const width = numberValue(dims?.width);
      const height = numberValue(dims?.height);
      const url = stringValue(raw.runtimeUrl);
      laneOutputs.push({
        id: outputId,
        ...(url ? { runtimeUrl: url } : {}),
        runtime,
        declaredSha256: declaredSha !== null && isSha256(declaredSha) ? declaredSha.toLowerCase() : ZERO_HASH,
        declaredBytes,
        runtimeHash: hashCheck,
        runtimeBytes: bytesCheck,
        ...(typeof raw.sourceRuntimeHashMatch === "boolean" ? { sourceRuntimeHashMatch: raw.sourceRuntimeHashMatch } : {}),
        ...(width !== null && height !== null ? { dimensions: { width, height } } : {}),
        ...(typeof raw.hasAlpha === "boolean" ? { hasAlpha: raw.hasAlpha } : {}),
      });
      integrityChecks[`output.${safeFileName(outputId)}.runtimeHash`] = hashCheck;
      integrityChecks[`output.${safeFileName(outputId)}.runtimeBytes`] = bytesCheck;
    }

    const declaredManifestSha = stringValue(source?.manifestSha256);
    const manifestExists = existsSync(manifestPath) && statSync(manifestPath).isFile();
    const manifestRef = manifestExists ? fileRef(manifestPath) : null;
    const manifestHash: ConsumerCheckStatus = manifestRef && declaredManifestSha !== null
      ? (manifestRef.sha256.toLowerCase() === declaredManifestSha.toLowerCase() ? "PASS" : "FAIL")
      : "NOT_CHECKED";
    integrityChecks.manifestHash = manifestHash;

    const primary = laneOutputs[0];
    const runtimeRef = primary.runtime;
    const primarySourcePath = stringValue(outputs[0].sourcePath);
    const sourceRef = primarySourcePath ? fileRef(primarySourcePath) : missingFileRef(join(laneRoot, dir, "source.png"));
    const runtimeInspection = inspectForConsumer(
      runtimeRef,
      "yeongheo-pixi-2d",
      "2d-image",
      `${runId}-ff-lane-${safeFileName(deliveryAssetId)}-runtime`,
      join(projectEvidenceRoot, `${safeFileName(deliveryAssetId)}-lane-runtime-clunk-inspection.json`),
      "runtime",
    );
    integrityChecks.runtimeClunk = runtimeInspection.record.inputHash === runtimeRef.sha256 ? "PASS" : "FAIL";

    const loaded = laneOutputs.every((output) => {
      const entry = runtimeAssets.find((candidate) => pathMatchesRuntime(candidate.url, output.runtime.path, root));
      return entry?.loaded === true;
    });
    const external = laneOutputs.some((output) => {
      const entry = runtimeAssets.find((candidate) => pathMatchesRuntime(candidate.url, output.runtime.path, root));
      return entry?.externalRequests === true;
    });
    const allRuntimePresent = laneOutputs.every((output) => output.runtime.hashVerified);
    const runtimeAttachment: ConsumerRuntimeAttachment = {
      status: loaded && !external && allRuntimePresent ? "PASS" : allRuntimePresent ? "GAP" : "FAIL",
      pathPresent: allRuntimePresent,
      observation: loaded && !external ? "LOADED" : allRuntimePresent ? "PATH_ONLY" : "NOT_OBSERVED",
      ...(loaded ? { loaded: true } : {}),
      ...(gameReadyPath ? { evidencePath: gameReadyPath } : {}),
      note: loaded
        ? "Lane runtime URL을 FF game-ready evidence에서 로드 확인했습니다."
        : "Lane 자산은 presentation/support(DOM·CSS) 경로이며 현재 game-ready runtime asset evidence에 대응 URL이 없어 경로·해시만 검증했습니다.",
    };

    const licenseStatus = stringValue(source?.licenseStatus);
    const provenanceRefs = [
      sidecarPath,
      ...(manifestExists ? [manifestPath] : []),
      ...laneOutputs.map((output) => output.runtime.path),
      ...outputs.map((raw) => stringValue(raw.sourcePath)).filter((path): path is string => path !== null),
    ].map((path) => resolve(path));
    const provenance: ConsumerProvenance = {
      status: manifestHash === "PASS" && licenseStatus !== null ? "PASS" : "GAP",
      refs: Array.from(new Set(provenanceRefs)),
      ...(manifestRef && manifestHash === "PASS" ? { manifestHash: manifestRef.sha256 } : {}),
      note: licenseStatus ? `licenseStatus=${licenseStatus}` : "라이선스 상태가 lane sidecar에 없습니다.",
    };

    const clunkRecord = asRecord(value.clunk);
    const lane: ConsumerLaneEvidence = {
      deliveryAssetId,
      sidecarPath: resolve(sidecarPath),
      ...(stringValue(value.runId) ? { runId: stringValue(value.runId)! } : {}),
      ...(stringValue(value.purpose) ? { purpose: stringValue(value.purpose)! } : {}),
      ...(stringValue(clunkRecord?.targetProfile) ? { targetProfile: stringValue(clunkRecord?.targetProfile)! } : {}),
      ...(manifestPath ? { manifestPath: resolve(manifestPath) } : {}),
      ...(declaredManifestSha !== null && isSha256(declaredManifestSha) ? { manifestSha256: declaredManifestSha.toLowerCase() } : {}),
      manifestHash,
      outputs: laneOutputs,
      productionReady: value.productionReady === true,
      ...(typeof value.runtimeVerified === "boolean" ? { runtimeVerified: value.runtimeVerified } : {}),
      ...(stringValue(value.playerFacing) ? { playerFacing: stringValue(value.playerFacing)! } : {}),
      humanReview: normalizeConsumerHumanReview(value.humanReview),
      ...(stringValue(value.evidenceKind) ? { evidenceKind: stringValue(value.evidenceKind)! } : {}),
    };

    assets.push({
      id: deliveryAssetId,
      projectId: "forge-front",
      kind: "2d-image",
      role: `FF presentation/support lane (vendor delivery): ${dir}`,
      source: sourceRef,
      runtime: runtimeRef,
      clunk: runtimeInspection.record,
      runtimeAttachment,
      provenance,
      integrity: checksToIntegrity(integrityChecks),
      lane,
    });
  }
  return assets;
}

function isSha256(value: string): boolean {
  return /^[a-f0-9]{64}$/i.test(value);
}

function normalizeConsumerHumanReview(value: unknown): "PASS" | "NO_GO" | "NOT_EVALUATED" {
  return value === "PASS" || value === "NO_GO" ? value : "NOT_EVALUATED";
}

function forgeRuntimeAssets(gameReady: Record<string, unknown>): Record<string, unknown>[] {
  const start = asRecord(gameReady.start);
  const nested = asRecord(start?.runtimeAssetEvidence);
  const direct = arrayRecords(nested?.assets);
  return direct.length > 0 ? direct : arrayRecords(gameReady.runtimeAssets);
}

function forgeRuntimeEvidence(
  root: string,
  candidate: RuntimeCandidate,
  runtimeAssets: readonly Record<string, unknown>[],
): ConsumerRuntimeEvidence {
  const value = candidate.value;
  const start = asRecord(value.start);
  const nested = asRecord(start?.runtimeAssetEvidence);
  const assets = runtimeAssets;
  const expected = numberValue(nested?.assetCount) ?? assets.length;
  const loaded = assets.filter((asset) => asset.loaded === true).length;
  const externalRequests = nested?.externalRequests === true || assets.some((asset) => asset.externalRequests === true);
  const pageErrors = arrayRecords(asRecord(value.runtimeErrors)?.pageErrors).length
    + arrayStrings(asRecord(value.runtimeErrors)?.errors).length
    + arrayStrings(asRecord(value.runtimeErrors)?.rejections).length;
  const resourceAudit = asRecord(value.resourceAudit);
  const external = arrayRecords(resourceAudit?.external).length;
  const captures = arrayStrings(value.captures).map((path) => fileRef(resolve(root, path)));
  const missingCapture = captures.some((file) => !file.hashVerified);
  const status = candidate.value.verdicts && !missingCapture && expected === loaded && !externalRequests && external === 0 && pageErrors === 0
    ? "PASS" as const
    : "FAIL" as const;
  return {
    status,
    scope: "project",
    ...(stringValue(value.runId) ? { runId: stringValue(value.runId)! } : {}),
    evidencePath: candidate.path,
    sourceCommit: null,
    shippedPath: true,
    expectedAssetCount: expected,
    loadedAssetCount: loaded,
    externalRequests,
    pageErrors,
    pageWarnings: 0,
    humanReview: stringValue(asRecord(value.verdicts)?.humanReview) === "PASS" ? "PASS" : "NOT_EVALUATED",
    productionReady: false,
    evidenceFiles: captures,
    note: "FORGE FRONT 자동 game-ready evidence에서 2D Clunk runtime asset URL·로드·외부 요청을 대조했습니다.",
  };
}

function runtimePathFromEvidence(root: string, runtimeAssets: readonly Record<string, unknown>[], record: ForgeManifestAsset): string | null {
  const candidate = runtimeAssets.find((entry) => {
    const url = stringValue(entry.url);
    return url !== null && (url.includes(`/assets/clunk/${record.id}/`) || url.toLowerCase().includes(record.id.replace(/-/g, "").toLowerCase()));
  });
  const url = candidate ? stringValue(candidate.url) : null;
  return url ? pathFromUrl(root, url) : null;
}

function pathMatchesRuntime(url: unknown, runtimePath: string, root: string): boolean {
  return typeof url === "string" && resolve(pathFromUrl(root, url)) === resolve(runtimePath);
}

function pathFromUrl(root: string, url: string): string {
  const pathname = url.split("?", 1)[0].replace(/^\/+/, "");
  return resolve(root, "public", ...pathname.split("/"));
}

function runHarvestVerifier(root: string, handoffPath: string): { status: ConsumerCheckStatus; output: unknown } {
  const verifier = join(root, "tools", "verify-clunk-handoff.cjs");
  if (!existsSync(verifier)) return { status: "NOT_CHECKED", output: null };
  try {
    const stdout = execFileSync(process.execPath, [verifier], {
      cwd: root,
      encoding: "utf8",
      env: { ...process.env, CLUNK_HANDOFF_MANIFEST: handoffPath },
      stdio: ["ignore", "pipe", "pipe"],
    });
    const parsed = JSON.parse(stdout) as Record<string, unknown>;
    return { status: parsed.status === "PASS" ? "PASS" : "FAIL", output: parsed };
  } catch (error) {
    const output = asRecord(error) ?? { error: error instanceof Error ? error.message : String(error) };
    return { status: "FAIL", output };
  }
}

function checksToIntegrity(checks: Record<string, ConsumerCheckStatus>): { status: "PASS" | "FAIL"; checks: Record<string, ConsumerCheckStatus> } {
  return {
    status: Object.values(checks).some((status) => status === "FAIL") ? "FAIL" : "PASS",
    checks,
  };
}

function matchesManifest(actual: ConsumerFileRef, expected: FileManifestRef | undefined): ConsumerCheckStatus {
  if (!expected || !actual.hashVerified) return "FAIL";
  return actual.sha256.toLowerCase() === String(expected.sha256 ?? "").toLowerCase()
    && actual.bytes === Number(expected.bytes)
    ? "PASS"
    : "FAIL";
}

function fileRef(filePath: string): ConsumerFileRef {
  const path = resolve(filePath);
  if (!existsSync(path) || !statSync(path).isFile()) return missingFileRef(path);
  const bytes = readFileSync(path);
  return { path, bytes: bytes.byteLength, sha256: sha256(bytes), hashVerified: true };
}

function missingFileRef(filePath: string): ConsumerFileRef {
  return { path: resolve(filePath), bytes: 0, sha256: ZERO_HASH, hashVerified: false };
}

function sha256(bytes: Uint8Array): string {
  return createHash("sha256").update(bytes).digest("hex");
}

function gitInfo(root: string): GitInfo {
  try {
    const head = execFileSync("git", ["-C", root, "rev-parse", "HEAD"], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim() || null;
    const status = execFileSync("git", ["-C", root, "status", "--porcelain"], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
    const dirtyEntryCount = status ? status.split(/\r?\n/).filter(Boolean).length : 0;
    return { head, dirty: dirtyEntryCount > 0, dirtyEntryCount };
  } catch {
    return { head: null, dirty: false, dirtyEntryCount: 0 };
  }
}

/**
 * A content hash of the Clunk executing code tree (packages/core/src + scripts).
 *
 * This binds the report to the exact bytes that produced it, so a report can no
 * longer claim a commit while running on different code (FORGE FRONT gap C-2):
 * the git HEAD gives commit context, the src hash reflects even uncommitted edits.
 */
function computeCoreBuildId(clunkRoot: string, git: GitInfo): string {
  const sourceRoots = [join(clunkRoot, "packages", "core", "src"), join(clunkRoot, "scripts")];
  const files = sourceRoots
    .flatMap((sourceRoot) => walkFiles(sourceRoot))
    .filter((file) => /\.(ts|mts|cts)$/.test(file))
    .sort((left, right) => left.localeCompare(right));
  const hash = createHash("sha256");
  for (const file of files) {
    hash.update(relative(clunkRoot, file).replace(/\\/g, "/"));
    hash.update("\0");
    hash.update(readFileSync(file));
    hash.update("\0");
  }
  const tree = hash.digest("hex").slice(0, 16);
  const head = git.head ? git.head.slice(0, 12) : "nogit";
  return `git:${head}${git.dirty ? "+dirty" : ""}+src:${tree}`;
}

function latestJson(root: string, predicate: (value: Record<string, unknown>) => boolean): RuntimeCandidate | null {
  if (!existsSync(root)) return null;
  const candidates: RuntimeCandidate[] = [];
  for (const filePath of walkFiles(root)) {
    if (extname(filePath).toLowerCase() !== ".json") continue;
    try {
      const value = JSON.parse(readFileSync(filePath, "utf8")) as Record<string, unknown>;
      if (predicate(value)) candidates.push({ path: filePath, value, modifiedAt: statSync(filePath).mtimeMs });
    } catch {
      // An unrelated or partially written evidence file must not stop the audit.
    }
  }
  candidates.sort((left, right) => right.modifiedAt - left.modifiedAt);
  return candidates[0] ?? null;
}

function walkFiles(root: string): string[] {
  const files: string[] = [];
  if (!existsSync(root)) return files;
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const path = join(root, entry.name);
    if (entry.isDirectory()) files.push(...walkFiles(path));
    else if (entry.isFile()) files.push(path);
  }
  return files;
}

function writeJsonExclusive(path: string, value: unknown): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, { encoding: "utf8", flag: "wx" });
}

function readRecord(path: string): Record<string, unknown> | null {
  try {
    return JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;
  } catch {
    return null;
  }
}

function arrayRecords(value: unknown): Record<string, unknown>[] {
  return Array.isArray(value) ? value.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === "object" && !Array.isArray(item))) : [];
}

function arrayStrings(value: unknown): string[] {
  return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];
}

function asRecord(value: unknown): Record<string, unknown> | null {
  return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : null;
}

function stringValue(value: unknown): string | null {
  return typeof value === "string" && value.trim() ? value.trim() : null;
}

function numberValue(value: unknown): number | null {
  return typeof value === "number" && Number.isFinite(value) ? value : null;
}

function passValue(value: unknown): boolean {
  return value === "PASS" || value === "pass" || value === "passed";
}

function safeFileName(value: string): string {
  return value.replace(/[^A-Za-z0-9._-]+/g, "-");
}

function stringPath(value: unknown): string | null {
  return typeof value === "string" && value.trim() ? value : null;
}

function assertOutputIsClunkOwned(outputPath: string, harvestRoot: string, forgeRoot: string): void {
  const path = resolve(outputPath);
  for (const consumerRoot of [resolve(harvestRoot), resolve(forgeRoot)]) {
    const rel = relative(consumerRoot, path);
    if (rel === "" || (!rel.startsWith("..") && !rel.startsWith(`..${pathSeparator()}`) && !isAbsolutePath(rel))) {
      throw new Error(`Consumer audit output must remain Clunk-owned: ${path}`);
    }
  }
}

function pathSeparator(): string {
  return "\\";
}

function isAbsolutePath(value: string): boolean {
  return /^[A-Za-z]:[\\/]/.test(value) || value.startsWith("\\\\") || value.startsWith("/");
}

main();
